/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CambiarClaveRouteImport } from './routes/cambiar-clave'
import { Route as AuthenticatedAlumnosRouteImport } from './routes/_authenticated/alumnos'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedCuerpoTecnicoRouteImport } from './routes/_authenticated/cuerpo-tecnico'
import { Route as AuthenticatedInfoRouteImport } from './routes/_authenticated/info'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMiHijoRouteImport } from './routes/_authenticated/mi-hijo'
import { Route as AuthenticatedPagosRouteImport } from './routes/_authenticated/pagos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiarClaveRoute = CambiarClaveRouteImport.update({
  id: '/cambiar-clave',
  path: '/cambiar-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlumnosRoute = AuthenticatedAlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuerpoTecnicoRoute =
  AuthenticatedCuerpoTecnicoRouteImport.update({
    id: '/cuerpo-tecnico',
    path: '/cuerpo-tecnico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfoRoute = AuthenticatedInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiHijoRoute = AuthenticatedMiHijoRouteImport.update({
  id: '/mi-hijo',
  path: '/mi-hijo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagosRoute = AuthenticatedPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cambiar-clave': typeof CambiarClaveRoute
  '/alumnos': typeof AuthenticatedAlumnosRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cuerpo-tecnico': typeof AuthenticatedCuerpoTecnicoRoute
  '/info': typeof AuthenticatedInfoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mi-hijo': typeof AuthenticatedMiHijoRoute
  '/pagos': typeof AuthenticatedPagosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cambiar-clave': typeof CambiarClaveRoute
  '/alumnos': typeof AuthenticatedAlumnosRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cuerpo-tecnico': typeof AuthenticatedCuerpoTecnicoRoute
  '/info': typeof AuthenticatedInfoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mi-hijo': typeof AuthenticatedMiHijoRoute
  '/pagos': typeof AuthenticatedPagosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cambiar-clave': typeof CambiarClaveRoute
  '/_authenticated/alumnos': typeof AuthenticatedAlumnosRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/cuerpo-tecnico': typeof AuthenticatedCuerpoTecnicoRoute
  '/_authenticated/info': typeof AuthenticatedInfoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/mi-hijo': typeof AuthenticatedMiHijoRoute
  '/_authenticated/pagos': typeof AuthenticatedPagosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cambiar-clave'
    | '/alumnos'
    | '/avisos'
    | '/cuerpo-tecnico'
    | '/info'
    | '/inicio'
    | '/mi-hijo'
    | '/pagos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cambiar-clave'
    | '/alumnos'
    | '/avisos'
    | '/cuerpo-tecnico'
    | '/info'
    | '/inicio'
    | '/mi-hijo'
    | '/pagos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cambiar-clave'
    | '/_authenticated/alumnos'
    | '/_authenticated/avisos'
    | '/_authenticated/cuerpo-tecnico'
    | '/_authenticated/info'
    | '/_authenticated/inicio'
    | '/_authenticated/mi-hijo'
    | '/_authenticated/pagos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CambiarClaveRoute: typeof CambiarClaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambiar-clave': {
      id: '/cambiar-clave'
      path: '/cambiar-clave'
      fullPath: '/cambiar-clave'
      preLoaderRoute: typeof CambiarClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alumnos': {
      id: '/_authenticated/alumnos'
      path: '/alumnos'
      fullPath: '/alumnos'
      preLoaderRoute: typeof AuthenticatedAlumnosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuerpo-tecnico': {
      id: '/_authenticated/cuerpo-tecnico'
      path: '/cuerpo-tecnico'
      fullPath: '/cuerpo-tecnico'
      preLoaderRoute: typeof AuthenticatedCuerpoTecnicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/info': {
      id: '/_authenticated/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof AuthenticatedInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-hijo': {
      id: '/_authenticated/mi-hijo'
      path: '/mi-hijo'
      fullPath: '/mi-hijo'
      preLoaderRoute: typeof AuthenticatedMiHijoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagos': {
      id: '/_authenticated/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AuthenticatedPagosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlumnosRoute: typeof AuthenticatedAlumnosRoute
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedCuerpoTecnicoRoute: typeof AuthenticatedCuerpoTecnicoRoute
  AuthenticatedInfoRoute: typeof AuthenticatedInfoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMiHijoRoute: typeof AuthenticatedMiHijoRoute
  AuthenticatedPagosRoute: typeof AuthenticatedPagosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlumnosRoute: AuthenticatedAlumnosRoute,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedCuerpoTecnicoRoute: AuthenticatedCuerpoTecnicoRoute,
  AuthenticatedInfoRoute: AuthenticatedInfoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMiHijoRoute: AuthenticatedMiHijoRoute,
  AuthenticatedPagosRoute: AuthenticatedPagosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CambiarClaveRoute: CambiarClaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
